export const MassageDescriptionType = {
  DeepTissueMassage: 'Deep Tissue Massage',
  HotStoneMassage: 'Hot Stone Massage',
  SportsMassage: 'Sports Massage',
  CouplesMassage: 'Couples Massage',
  Acupuncture: 'Acupuncture',
  AromatherapyMassage: 'Aromatherapy Massage',
  ThaiMassage: 'Thai Massage',
  SwedishMassage: 'Swedish Massage',
  Shiatsu: 'Shiatsu',
  Reflexology: 'Reflexology',
  LymphaticMassage: 'Lymphatic Massage',
  TriggerPointTherapy: 'Trigger Point Therapy',
  Acupressure: 'Acupressure',
  CuppingTherapy: 'Cupping Therapy',
  HerbalCompressMassage: 'Herbal Compress Massage',
  ScalpMassage: 'Scalp Massage',
  BarefootBarTherapy: 'Barefoot Bar Therapy',
  NeuromuscularTherapy: 'Neuromuscular Therapy',
  RemedialMassage: 'Remedial Massage',
  FootMassage: 'Foot Massage',
  SpaMassage: 'Spa Massage',
} as const;
